apiVersion: v1
kind: Service
metadata:
  name: n8n-service
  namespace: home
  annotations:
    tailscale.com/expose: "true"
    tailscale.com/proxy-class: "proxyclasses.tailscale.com"
spec:
  type: LoadBalancer
  selector:
    app: n8n
  ports:
    - protocol: TCP
      port: 5678
      targetPort: 5678
