apiVersion: v1
kind: Service
metadata:
    name: n8n-service
spec:
    type: LoadBalancer
    loadBalancerClass: tailscale
    ports:
        - port: 5678
          targetPort: 5678
          protocol: TCP
          name: n8n-port
    selector:
        app: n8n
