apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: home

helmGlobals:
    chartHome: ../charts

helmCharts:
    - name: nginx
      version: 0.1.0
      releaseName: nginx
      namespace: home
      valuesInline:
          replicaCount: 2
